#!/usr/bin/env bash
# oh-my-longfor environment variable template generator
# Provides: .env template generation, env var status checking
set -euo pipefail

# shellcheck source=lib/common.sh
# source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

# Default OML home (should be sourced from common.sh)
OML_HOME="${OML_HOME:-$HOME/.oml}"

# Generate a .env template file from manifest env var definitions
# Usage: oml_generate_env_template <manifest-path>
oml_generate_env_template() {
  local manifest_file="$1"
  local template_dir="${OML_HOME}/env"
  local template_file="${template_dir}/.env.template"

  mkdir -p "$template_dir"

  if ! command -v python3 >/dev/null 2>&1; then
    oml_error "python3 is required to generate the .env template"
    return 1
  fi

  if [ ! -f "$manifest_file" ]; then
    oml_error "Manifest file not found: $manifest_file"
    return 1
  fi

  oml_info "Generating .env template → $template_file"

  python3 - "$manifest_file" "$template_file" << 'PYEOF'
import sys
import yaml
from datetime import datetime

manifest_path = sys.argv[1]
output_path   = sys.argv[2]

try:
    with open(manifest_path) as f:
        data = yaml.safe_load(f)
except yaml.YAMLError as e:
    print(f'[oml] ERROR: Invalid YAML in manifest: {e}', file=sys.stderr)
    sys.exit(1)
if data is None:
    print('[oml] ERROR: Manifest file is empty or invalid', file=sys.stderr)
    sys.exit(1)

env_vars = data.get('env', [])
lines = [
    "# oh-my-longfor Environment Variables",
    f"# Generated by oml on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
    "#",
    "# USAGE:",
    "#   1. Copy this file: cp ~/.oml/env/.env.template ~/.env.oml",
    "#   2. Fill in your values in ~/.env.oml",
    '#   3. Add to your shell rc: [ -f ~/.env.oml ] && source ~/.env.oml',
    "#",
    "# Run 'oml env' to check which variables are set.",
    "",
]

required_vars = [v for v in env_vars if v.get('required', True)]
optional_vars = [v for v in env_vars if not v.get('required', True)]

if required_vars:
    lines.append("# ─── Required ──────────────────────────────────────────────────────────")
    for v in required_vars:
        lines.append(f"# {v.get('description', '')}")
        lines.append(f"{v['name']}=")
        lines.append("")

if optional_vars:
    lines.append("# ─── Optional ──────────────────────────────────────────────────────────")
    for v in optional_vars:
        lines.append(f"# {v.get('description', '')}")
        lines.append(f"{v['name']}=")
        lines.append("")

with open(output_path, 'w') as f:
    f.write('\n'.join(lines))

print(f"Generated {output_path} with {len(env_vars)} variables ({len(required_vars)} required, {len(optional_vars)} optional)")
PYEOF

  oml_success "Generated .env template at $template_file"
}

# Check which required env vars are set vs missing (does NOT display values)
# Usage: oml_check_env <manifest-path>
oml_check_env() {
  local manifest_file="$1"

  if ! command -v python3 >/dev/null 2>&1; then
    oml_error "python3 is required to check env var status"
    return 1
  fi

  if [ ! -f "$manifest_file" ]; then
    oml_error "Manifest file not found: $manifest_file"
    return 1
  fi

  python3 - "$manifest_file" << 'PYEOF'
import sys
import yaml
import os

try:
    with open(sys.argv[1]) as f:
        data = yaml.safe_load(f)
except yaml.YAMLError as e:
    print(f'[oml] ERROR: Invalid YAML in manifest: {e}', file=sys.stderr)
    sys.exit(1)
if data is None:
    print('[oml] ERROR: Manifest file is empty or invalid', file=sys.stderr)
    sys.exit(1)

env_vars = data.get('env', [])
all_set = True

print("Environment Variable Status:")
print("")

for v in env_vars:
    name     = v.get('name', '')
    required = v.get('required', True)
    is_set   = bool(os.environ.get(name))
    status   = "\033[0;32m✅ set\033[0m" if is_set else "\033[0;31m❌ missing\033[0m"
    req_tag  = " (required)" if required else " (optional)"
    print(f"  {status}  {name}{req_tag}")
    if not is_set and required:
        all_set = False

print("")
if all_set:
    print("\033[0;32mAll required env vars are set.\033[0m")
else:
    print("\033[1;33mSome required env vars are missing. Fill in ~/.env.oml and source it.\033[0m")
    sys.exit(1)
PYEOF
}

# Output the shell rc line needed to source the .env.oml file
# Usage: oml_env_source_line
oml_env_source_line() {
  echo '[ -f ~/.env.oml ] && source ~/.env.oml'
}
