#!/usr/bin/env bash
# oh-my-longfor environment variable template generator
# Provides: .env template generation, env var status checking
set -euo pipefail

# shellcheck source=lib/common.sh
# source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

# Default OML home (should be sourced from common.sh)
OML_HOME="${OML_HOME:-$HOME/.oml}"

# Generate a .env template file from manifest env var definitions
# Usage: oml_generate_env_template <manifest-path>
oml_generate_env_template() {
  local manifest_file="$1"
  local template_dir="${OML_HOME}/env"
  local template_file="${template_dir}/.env.template"

  mkdir -p "$template_dir"

  if ! command -v bun >/dev/null 2>&1; then
    oml_error "bun is required to generate the .env template"
    return 1
  fi

  if [ ! -f "$manifest_file" ]; then
    oml_error "Manifest file not found: $manifest_file"
    return 1
  fi

  oml_info "Generating .env template → $template_file"

  local tmp_manifest
  tmp_manifest=$(mktemp)
  if ! bunx -y js-yaml "$manifest_file" > "$tmp_manifest" 2>/dev/null; then
    oml_error "Invalid YAML in manifest: $manifest_file"
    rm -f "$tmp_manifest"
    return 1
  fi

  bun - "$tmp_manifest" "$template_file" << 'BUNEOF'
const fs = require('fs');

const manifestPath = process.argv[2];
const outputPath = process.argv[3];

let manifest = {};
try { manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8')); } catch (e) {}

const envVars = manifest.env || [];

const now = new Date();
const formattedDate = now.toISOString().replace('T', ' ').substring(0, 16) + ' UTC';

const lines = [
  '# oh-my-longfor Environment Variables',
  `# Generated by oml on ${formattedDate}`,
  '#',
  '# USAGE:',
  '#   1. Copy this file: cp ~/.oml/env/.env.template ~/.env.oml',
  '#   2. Fill in your values in ~/.env.oml',
  '#   3. Add to your shell rc: [ -f ~/.env.oml ] && source ~/.env.oml',
  '#',
  "# Run 'oml env' to check which variables are set.",
  '',
];

const requiredVars = envVars.filter(v => v.required !== false);
const optionalVars = envVars.filter(v => v.required === false);

if (requiredVars.length > 0) {
  lines.push('# ─── Required ──────────────────────────────────────────────────────────');
  for (const v of requiredVars) {
    if (v.description) lines.push(`# ${v.description}`);
    lines.push(`${v.name}=`);
    lines.push('');
  }
}

if (optionalVars.length > 0) {
  lines.push('# ─── Optional ──────────────────────────────────────────────────────────');
  for (const v of optionalVars) {
    if (v.description) lines.push(`# ${v.description}`);
    lines.push(`${v.name}=`);
    lines.push('');
  }
}

fs.writeFileSync(outputPath, lines.join('\n'));
console.log(`Generated ${outputPath} with ${envVars.length} variables (${requiredVars.length} required, ${optionalVars.length} optional)`);
BUNEOF

  rm -f "$tmp_manifest"
  oml_success "Generated .env template at $template_file"
}

# Check which required env vars are set vs missing (does NOT display values)
# Usage: oml_check_env <manifest-path>
oml_check_env() {
  local manifest_file="$1"

  if ! command -v bun >/dev/null 2>&1; then
    oml_error "bun is required to check env var status"
    return 1
  fi

  if [ ! -f "$manifest_file" ]; then
    oml_error "Manifest file not found: $manifest_file"
    return 1
  fi

  local tmp_manifest
  tmp_manifest=$(mktemp)
  if ! bunx -y js-yaml "$manifest_file" > "$tmp_manifest" 2>/dev/null; then
    oml_error "Invalid YAML in manifest: $manifest_file"
    rm -f "$tmp_manifest"
    return 1
  fi

  bun - "$tmp_manifest" << 'BUNEOF'
const fs = require('fs');

const manifestPath = process.argv[2];

let manifest = {};
try { manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8')); } catch (e) {}

const envVars = manifest.env || [];

console.log('Environment Variable Status:\n');

// ── No env vars declared in manifest at all ─────────────────────────────────
if (envVars.length === 0) {
  console.log('  (No env vars are declared in this manifest.)');
  console.log('');
  console.log('\x1b[0;34m[oml]\x1b[0m To track API keys, add an \x1b[0;33menv:\x1b[0m block to your manifest.yaml.');
  process.exit(0);
}

let missingRequired = 0;

for (const v of envVars) {
  const name = v.name || '';
  if (!name) continue;

  const required = v.required !== false;
  const isSet   = !!process.env[name];

  const status = isSet ? '\x1b[0;32m\u2705 set\x1b[0m' : '\x1b[0;31m\u274c missing\x1b[0m';
  const reqTag = required ? ' (required)' : ' (optional)';

  console.log(`  ${status}  ${name}${reqTag}`);

  if (!isSet && required) missingRequired++;
}

console.log('');
const requiredCount = envVars.filter(v => v.required !== false).length;
if (missingRequired === 0) {
  console.log(`\x1b[0;32mAll ${requiredCount} required env var(s) are set.\x1b[0m`);
} else {
  console.log(`\x1b[1;33m${missingRequired} required env var(s) missing.\x1b[0m Edit ~/.oml/env/.env.oml and source it.`);
  process.exit(1);
}
BUNEOF

  local exit_code=$?
  rm -f "$tmp_manifest"
  return $exit_code
}

# Output the shell rc line needed to source the .env.oml file
# Usage: oml_env_source_line
oml_env_source_line() {
  local env_file="${OML_HOME}/env/.env.oml"
  echo "[ -f \"${env_file}\" ] && source \"${env_file}\""
}

# Copy .env.template to .env.oml if the file does not exist yet (non-destructive).
# Called automatically after a non-vanilla install so users only need to edit,
# not first copy, the env file.
# Usage: oml_setup_env_file
oml_setup_env_file() {
  local template_file="${OML_HOME}/env/.env.template"
  local env_file="${OML_HOME}/env/.env.oml"

  if [ ! -f "$template_file" ]; then
    oml_warn "No .env.template found \u2014 skipping env file creation"
    return 0
  fi

  if [ -f "$env_file" ]; then
    oml_info "Env file already exists: $env_file (skipping copy)"
    return 0
  fi

  cp "$template_file" "$env_file"
  oml_success "Created env file: $env_file"
}
