#!/usr/bin/env bash
# oh-my-longfor environment variable template generator
# Provides: .env template generation, env var status checking
set -euo pipefail

# shellcheck source=lib/common.sh
# source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

# Default OML home (should be sourced from common.sh)
OML_HOME="${OML_HOME:-$HOME/.oml}"

# Generate a .env template file from manifest env var definitions
# Usage: oml_generate_env_template <manifest-path>
oml_generate_env_template() {
  local manifest_file="$1"
  local template_dir="${OML_HOME}/env"
  local template_file="${template_dir}/.env.template"

  mkdir -p "$template_dir"

  if ! command -v bun >/dev/null 2>&1; then
    oml_error "bun is required to generate the .env template"
    return 1
  fi

  if [ ! -f "$manifest_file" ]; then
    oml_error "Manifest file not found: $manifest_file"
    return 1
  fi

  oml_info "Generating .env template → $template_file"

  local tmp_manifest
  tmp_manifest=$(mktemp)
  if ! bunx -y js-yaml "$manifest_file" > "$tmp_manifest" 2>/dev/null; then
    oml_error "Invalid YAML in manifest: $manifest_file"
    rm -f "$tmp_manifest"
    return 1
  fi

  bun - "$tmp_manifest" "$template_file" << 'BUNEOF'
const fs = require('fs');

const manifestPath = process.argv[2];
const outputPath = process.argv[3];

let manifest = {};
try { manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8')); } catch (e) {}

const envVars = manifest.env || [];

const now = new Date();
const formattedDate = now.toISOString().replace('T', ' ').substring(0, 16) + ' UTC';

const lines = [
  '# oh-my-longfor Environment Variables',
  `# Generated by oml on ${formattedDate}`,
  '#',
  '# USAGE:',
  '#   1. Copy this file: cp ~/.oml/env/.env.template ~/.env.oml',
  '#   2. Fill in your values in ~/.env.oml',
  '#   3. Add to your shell rc: [ -f ~/.env.oml ] && source ~/.env.oml',
  '#',
  "# Run 'oml env' to check which variables are set.",
  '',
];

const requiredVars = envVars.filter(v => v.required !== false);
const optionalVars = envVars.filter(v => v.required === false);

if (requiredVars.length > 0) {
  lines.push('# ─── Required ──────────────────────────────────────────────────────────');
  for (const v of requiredVars) {
    if (v.description) lines.push(`# ${v.description}`);
    lines.push(`${v.name}=`);
    lines.push('');
  }
}

if (optionalVars.length > 0) {
  lines.push('# ─── Optional ──────────────────────────────────────────────────────────');
  for (const v of optionalVars) {
    if (v.description) lines.push(`# ${v.description}`);
    lines.push(`${v.name}=`);
    lines.push('');
  }
}

fs.writeFileSync(outputPath, lines.join('\n'));
console.log(`Generated ${outputPath} with ${envVars.length} variables (${requiredVars.length} required, ${optionalVars.length} optional)`);
BUNEOF

  rm -f "$tmp_manifest"
  oml_success "Generated .env template at $template_file"
}

# Check which required env vars are set vs missing (does NOT display values)
# Usage: oml_check_env <manifest-path>
oml_check_env() {
  local manifest_file="$1"

  if ! command -v bun >/dev/null 2>&1; then
    oml_error "bun is required to check env var status"
    return 1
  fi

  if [ ! -f "$manifest_file" ]; then
    oml_error "Manifest file not found: $manifest_file"
    return 1
  fi

  local tmp_manifest
  tmp_manifest=$(mktemp)
  if ! bunx -y js-yaml "$manifest_file" > "$tmp_manifest" 2>/dev/null; then
    oml_error "Invalid YAML in manifest: $manifest_file"
    rm -f "$tmp_manifest"
    return 1
  fi

  bun - "$tmp_manifest" << 'BUNEOF'
const fs = require('fs');

const manifestPath = process.argv[2];

let manifest = {};
try { manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8')); } catch (e) {}

const envVars = manifest.env || [];
let allSet = true;

console.log('Environment Variable Status:\n');

for (const v of envVars) {
  const name = v.name || '';
  if (!name) continue;
  
  const required = v.required !== false;
  const isSet = !!process.env[name];
  
  const status = isSet ? '\x1b[0;32m✅ set\x1b[0m' : '\x1b[0;31m❌ missing\x1b[0m';
  const reqTag = required ? ' (required)' : ' (optional)';
  
  console.log(`  ${status}  ${name}${reqTag}`);
  
  if (!isSet && required) {
    allSet = false;
  }
}

console.log('');
if (allSet) {
  console.log('\x1b[0;32mAll required env vars are set.\x1b[0m');
} else {
  console.log('\x1b[1;33mSome required env vars are missing. Fill in ~/.env.oml and source it.\x1b[0m');
  process.exit(1);
}
BUNEOF

  local exit_code=$?
  rm -f "$tmp_manifest"
  return $exit_code
}

# Output the shell rc line needed to source the .env.oml file
# Usage: oml_env_source_line
oml_env_source_line() {
  echo '[ -f ~/.env.oml ] && source ~/.env.oml'
}
